version: '3.5'

networks:
  frontend:
    ## Use a custom driver
    #driver: frontend-driver
    driver: bridge
    name: frontend
  dbnet:
    external:
      name: dbnet


services:
  webcoremongo:
    image: ${DOCKER_REGISTRY-}webcoremongo
    container_name: webmongoapp
    build:
      context: .
      dockerfile: WebCoreMongo/Dockerfile
    networks:
      - dbnet
      - frontend
    #links:
     # - webapp
 
  webapp:
    image: ${DOCKER_REGISTRY-}webapp
    container_name: apiapp
    build:
      context: .
      dockerfile: WebApp/Dockerfile
    networks:
      - frontend
